// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class AgentsResource {
  constructor(private readonly transport: Transport) {}

  async v1AgentsIndex(): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/agents', null, null);
  }

  async v1AgentsStore(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/agents', null, params);
  }

  async v1AgentsRunsShow(run: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/agents/runs/${run}`, null, null);
  }

  async v1AgentsShow(agent: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/agents/${agent}`, null, null);
  }

  async v1AgentsUpdate(agent: string, params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('PATCH', `/agents/${agent}`, null, params);
  }

  async v1AgentsVersionsIndex(agent: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/agents/${agent}/versions`, null, null);
  }

  async v1AgentsVersionsStore(agent: string, params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', `/agents/${agent}/versions`, null, params);
  }

  async v1AgentsVersionsShow(agent: string, version: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/agents/${agent}/versions/${version}`, null, null);
  }

  async v1AgentsRunsStore(agent: string, params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', `/agents/${agent}/runs`, null, params);
  }
}
