// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class AuditLogsResource {
  constructor(private readonly transport: Transport) {}

  async list(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/audit-logs', query, null);
  }

  async get(uuid: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/audit-logs/${uuid}`, null, null);
  }
}
