// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class ChatResource {
  constructor(private readonly transport: Transport) {}

  async create(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/chat/completions', null, params);
  }

  async *createStreamed(params: Record<string, unknown> = {}): AsyncGenerator<Record<string, unknown>> {
    yield* this.transport.stream('POST', '/chat/completions', params);
  }
}
