// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class EmbeddingsResource {
  constructor(private readonly transport: Transport) {}

  async create(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/embeddings', null, params);
  }
}
