// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class MemoryResource {
  constructor(private readonly transport: Transport) {}

  async listThreads(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/memory/threads', query, null);
  }

  async createThread(): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/memory/threads', null, null);
  }

  async getThread(thread: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/memory/threads/${thread}`, null, null);
  }

  async deleteThread(thread: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/memory/threads/${thread}`, null, null);
  }

  async search(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/memory/search', null, params);
  }

  async listFacts(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/memory/facts', query, null);
  }

  async rememberFact(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/memory/facts', null, params);
  }

  async forgetFact(id: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/memory/facts/${id}`, null, null);
  }

  async export(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/memory/export', query, null);
  }

  async erase(): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', '/memory', null, null);
  }

  async listDocuments(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/memory/documents', query, null);
  }

  async ingestDocument(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/memory/documents', null, params);
  }

  async getDocument(document: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/memory/documents/${document}`, null, null);
  }

  async deleteDocument(document: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/memory/documents/${document}`, null, null);
  }

  async listCollections(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/memory/collections', query, null);
  }

  async createCollection(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/memory/collections', null, params);
  }

  async getCollection(slug: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/memory/collections/${slug}`, null, null);
  }

  async deleteCollection(slug: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/memory/collections/${slug}`, null, null);
  }

  async updateCollection(slug: string, params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('PATCH', `/memory/collections/${slug}`, null, params);
  }
}
