// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class MemoryThreadsResource {
  constructor(private readonly transport: Transport) {}

  async list(): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/memory/threads', null, null);
  }

  async create(): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/memory/threads', null, null);
  }

  async get(thread: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/memory/threads/${thread}`, null, null);
  }

  async delete(thread: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/memory/threads/${thread}`, null, null);
  }
}
