// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class MemoryResource {
  constructor(private readonly transport: Transport) {}

  async forget(): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', '/memory', null, null);
  }
}
