// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class ModelsResource {
  constructor(private readonly transport: Transport) {}

  async list(): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/models', null, null);
  }
}
