// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { Transport } from "../client/transport.js";

export class RecallResource {
  constructor(private readonly transport: Transport) {}

  async listThreads(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/recall/threads', query, null);
  }

  async createThread(): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/recall/threads', null, null);
  }

  async getThread(thread: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/recall/threads/${thread}`, null, null);
  }

  async deleteThread(thread: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/recall/threads/${thread}`, null, null);
  }

  async search(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/recall/search', null, params);
  }

  async searchFacts(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/recall/facts/search', null, params);
  }

  async listFacts(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/recall/facts', query, null);
  }

  async rememberFact(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/recall/facts', null, params);
  }

  async forgetFact(id: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/recall/facts/${id}`, null, null);
  }

  async export(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/recall/export', query, null);
  }

  async erase(): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', '/recall', null, null);
  }

  async searchDocuments(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/recall/documents/search', null, params);
  }

  async listDocuments(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/recall/documents', query, null);
  }

  async ingestDocument(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/recall/documents', null, params);
  }

  async getDocument(document: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/recall/documents/${document}`, null, null);
  }

  async deleteDocument(document: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/recall/documents/${document}`, null, null);
  }

  async listCollections(query: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('GET', '/recall/collections', query, null);
  }

  async createCollection(params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('POST', '/recall/collections', null, params);
  }

  async getCollection(slug: string): Promise<Record<string, unknown>> {
    return this.transport.request('GET', `/recall/collections/${slug}`, null, null);
  }

  async deleteCollection(slug: string): Promise<Record<string, unknown>> {
    return this.transport.request('DELETE', `/recall/collections/${slug}`, null, null);
  }

  async updateCollection(slug: string, params: Record<string, unknown> = {}): Promise<Record<string, unknown>> {
    return this.transport.request('PATCH', `/recall/collections/${slug}`, null, params);
  }
}
