// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

export interface AuditLogApiResource {
  id: string;
  component: string;
  action: string;
  actorId: number | null;
  ipAddress: string | null;
  userAgent: string | null;
  target: unknown | null;
  metadata: unknown | null;
  createdAt: string | null;
}
