// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

export interface AuditLogApiResource {
  id: string;
  component: string;
  action: string;
  actor_id: number | null;
  ip_address: string | null;
  user_agent: string | null;
  target: unknown | null;
  metadata: unknown | null;
  created_at: string | null;
}
