// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

export interface ChatCompletionsRequest {
  messages: unknown[];
  model?: string;
  models?: string[];
  provider?: unknown;
  temperature?: number | null;
  max_tokens?: number | null;
  stream?: boolean | null;
  stream_options?: unknown;
  firewall?: boolean | null;
  collection?: string[] | null;
  user?: string | null;
  thread?: string | null;
  tags?: string[] | null;
  name?: string | null;
  top_p?: number | null;
  stop?: string[] | null;
  presence_penalty?: number | null;
  frequency_penalty?: number | null;
  n?: number | null;
  seed?: number | null;
  logit_bias?: number[] | null;
  logprobs?: boolean | null;
  top_logprobs?: number | null;
  max_completion_tokens?: number | null;
  tools?: unknown[] | null;
  tool_choice?: string | null;
  parallel_tool_calls?: boolean | null;
  cache?: boolean | null;
  response_format?: unknown;
}
