// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

export interface ChatCompletionsRequest {
  model: string;
  messages: unknown[];
  temperature?: number | null;
  max_tokens?: number | null;
  stream?: boolean | null;
  firewall?: boolean | null;
  rag?: string | null;
  user?: string | null;
  thread?: string | null;
  top_p?: number | null;
  presence_penalty?: number | null;
  frequency_penalty?: number | null;
  n?: number | null;
  seed?: number | null;
  logprobs?: boolean | null;
  top_logprobs?: number | null;
  max_completion_tokens?: number | null;
  tool_choice?: string | null;
  parallel_tool_calls?: boolean | null;
  cache?: boolean | null;
  stop?: string[] | null;
  logit_bias?: number[] | null;
  response_format?: unknown;
  tools?: unknown[] | null;
}
