// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

export interface EmbeddingsRequest {
  model: string;
  input: string[];
  encoding_format?: string | null;
  dimensions?: number | null;
  user?: string | null;
}
