// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

export interface SearchFactsRequest {
  query: string;
  collection?: string[] | null;
  user_ref?: string | null;
  limit?: number | null;
}
