// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

export interface StoreScoreRequest {
  request_id: string;
  name: string;
  value?: number;
  value_string?: string;
  comment?: string | null;
}
