// AUTO-GENERATED by akumi/codegen. Do not edit by hand.

import type { ClientConfig } from "./client/config.js";
import { Transport } from "./client/transport.js";
import { AgentsResource } from "./resources/agents.js";
import { AuditLogResource } from "./resources/auditLog.js";
import { ChatCompletionsResource } from "./resources/chatCompletions.js";
import { EmbeddingsResource } from "./resources/embeddings.js";
import { MemoryResource } from "./resources/memory.js";
import { ModelsResource } from "./resources/models.js";
import { ScoresResource } from "./resources/scores.js";

export class Akumi {
  private readonly transport: Transport;
  readonly agents: AgentsResource;
  readonly auditLog: AuditLogResource;
  readonly chatCompletions: ChatCompletionsResource;
  readonly embeddings: EmbeddingsResource;
  readonly memory: MemoryResource;
  readonly models: ModelsResource;
  readonly scores: ScoresResource;
  constructor(config: ClientConfig) {
    this.transport = new Transport(config);
    this.agents = new AgentsResource(this.transport);
    this.auditLog = new AuditLogResource(this.transport);
    this.chatCompletions = new ChatCompletionsResource(this.transport);
    this.embeddings = new EmbeddingsResource(this.transport);
    this.memory = new MemoryResource(this.transport);
    this.models = new ModelsResource(this.transport);
    this.scores = new ScoresResource(this.transport);
  }

  static fromApiKey(apiKey: string): Akumi {
    return new Akumi({ apiKey });
  }
}
